ALTER TABLE mfg_orders
  ADD COLUMN IF NOT EXISTS tax_amount   NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS samples_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS per_unit_cost NUMERIC(10,4);
